# Generated by Django 2.2.6 on 2019-10-17 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_cups', models.IntegerField(verbose_name='Codígo')),
                ('Abreviatura', models.CharField(max_length=200, verbose_name='Abreviatura')),
                ('Nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('Descripcion', models.TextField(max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Diagnostico',
                'verbose_name_plural': 'Diagnosticos',
                'ordering': ['Nombre'],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('Identificacion_medico', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('PrimerApellido', models.CharField(max_length=200, verbose_name='Primer apellido')),
                ('SegundoApellido', models.CharField(max_length=200, verbose_name='Segundo apellido')),
                ('Sexo', models.CharField(max_length=200, verbose_name='Genero')),
                ('Email', models.EmailField(max_length=200, verbose_name='Email')),
                ('Telefeno', models.IntegerField(verbose_name='Teléfono')),
                ('Residencia', models.CharField(max_length=200, verbose_name='Residencia')),
                ('Ciudad', models.TextField(max_length=200, verbose_name='Ciudad')),
                ('Departamento', models.TextField(max_length=200, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['Nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('Identificacion_paciente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificación')),
                ('Nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('PrimerApellido', models.CharField(max_length=200, verbose_name='Primer apellido')),
                ('SegundoApellido', models.CharField(max_length=200, verbose_name='Segundo apellido')),
                ('Fecha_nacimiento', models.DateField(max_length=200, verbose_name='Nacimiento')),
                ('Sexo', models.CharField(max_length=200, verbose_name='Sexo')),
                ('Ocupacion', models.CharField(max_length=200, verbose_name='Ocupación')),
                ('Email', models.EmailField(max_length=200, verbose_name='Email')),
                ('Telefeno', models.CharField(max_length=200, verbose_name='Teléfono')),
                ('Residencia', models.CharField(max_length=200, verbose_name='Residencia')),
                ('Ciudad', models.CharField(max_length=200, verbose_name='Ciudad')),
                ('Departamento', models.CharField(max_length=200, verbose_name='Depatamento')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['Nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('Identificacion_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('Ciudad', models.CharField(max_length=200, verbose_name='Ciudad')),
                ('Departamento', models.CharField(max_length=200, verbose_name='Departamento')),
                ('Producto', models.CharField(max_length=200, verbose_name='Producto')),
                ('Cantidad', models.IntegerField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['Nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_cups', models.IntegerField(verbose_name='Codígo')),
                ('Abreviatura', models.CharField(max_length=200, verbose_name='Abreviatura')),
                ('Nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('Descripcion', models.TextField(max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['Nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Identificacion_usario', models.AutoField(primary_key=True, serialize=False)),
                ('Usuario', models.CharField(max_length=200, verbose_name='Usuario')),
                ('Email', models.EmailField(max_length=200, verbose_name='Email')),
                ('Rol', models.CharField(max_length=200, verbose_name='Rol')),
                ('Password', models.CharField(max_length=200, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['Usuario'],
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('Identificacion_nomina', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_inicio', models.DateTimeField(verbose_name='Fecha inicio')),
                ('Fecha_fin', models.DateTimeField(verbose_name='Fecha fin')),
                ('Detalle', models.TextField(verbose_name='Detalle')),
                ('Identificacion_especialista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estetica.Medico', verbose_name='Identificación Medico')),
            ],
            options={
                'verbose_name': 'Nomina',
                'verbose_name_plural': 'Nominas',
                'ordering': ['Detalle'],
            },
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('Identificacion_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('Cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('Cantidad_salida', models.IntegerField(verbose_name='Cantidad de salida')),
                ('Existencia', models.IntegerField(verbose_name='Existencia')),
                ('Fecha_ingreso', models.DateTimeField(max_length=200, verbose_name='Fecha de ingreso')),
                ('Fecha_vencimiento', models.DateTimeField(max_length=200, null=True, verbose_name='Fecha de caducidad')),
                ('Id_Proveedor', models.ManyToManyField(to='estetica.Proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Isumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['Nombre'],
            },
        ),
        migrations.CreateModel(
            name='Historia_clinica',
            fields=[
                ('Identificacion_historia', models.IntegerField(primary_key=True, serialize=False)),
                ('Fecha_inicio', models.DateField(max_length=200, verbose_name='Fecha de inicio')),
                ('Fecha_fin', models.DateField(max_length=200, verbose_name='Fecha fin')),
                ('Motivo_consulta', models.TextField(max_length=200, verbose_name='Motivo de consulta')),
                ('Consecutivo', models.IntegerField(verbose_name='Consecutivo')),
                ('Servicio', models.TextField(max_length=200, verbose_name='Servicio')),
                ('Anexo', models.TextField(max_length=200, verbose_name='Anexo')),
                ('Antecedentes', models.TextField(max_length=200, null=True, verbose_name='Antecedentes')),
                ('Diagnostico_codigo', models.ManyToManyField(to='estetica.Diagnostico', verbose_name='Diagnostico')),
                ('Id_Medico', models.ManyToManyField(to='estetica.Medico', verbose_name='Medico')),
                ('Paciente_Nombre', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='estetica.Paciente')),
            ],
            options={
                'verbose_name': 'Historia',
                'verbose_name_plural': 'Historias',
                'ordering': ['Servicio'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('Identificacion_factura', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('Valor', models.IntegerField(verbose_name='Valor')),
                ('Iva', models.IntegerField(verbose_name='Iva')),
                ('Fecha_factura', models.DateTimeField(null=True, verbose_name='Fecha')),
                ('Subtotal', models.IntegerField(verbose_name='Subtotal')),
                ('Total', models.IntegerField(verbose_name='Total')),
                ('Detalle', models.ManyToManyField(to='estetica.Servicio', verbose_name='Detalle')),
                ('Fact_hisCllin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='estetica.Historia_clinica', verbose_name='Historia Clínica')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['Cantidad'],
            },
        ),
    ]
